# Model + Define, Train & Study

This stage focuses on selecting suitable classification algorithms for the **AI Coding Agent Identification** problem.

The target variable `agent` is a multiclass categorical variable with 6 classes.

The selected classification models will be loaded using Python and trained using the saved P1 feature-engineered training data from the Feature Engineering stage.

In [1]:
# Import libraries and create a connection to the AIDev MySQL database

import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:root@localhost:3306/aidev_project",
    pool_pre_ping=True,
    connect_args={
        "connect_timeout": 60,
        "read_timeout": 600,
        "write_timeout": 600
    }
)

print("Database connection created successfully.")

Database connection created successfully.


In [2]:
# Load P1 feature-engineered training and testing data

from scipy.sparse import load_npz
import numpy as np

# Load feature matrices
X_train = load_npz("X_p1_train_final.npz")
X_test = load_npz("X_p1_test_final.npz")

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (2195082, 5330)
X_test shape: (548771, 5330)


In [3]:
# Load P1 target variable: agent
# Use row_order to guarantee alignment with the feature matrices.

query = """
SELECT
    row_order,
    split,
    agent
FROM ml_p1_split
ORDER BY row_order
"""

df_p1_split = pd.read_sql(
    query,
    engine
)

print("P1 target data loaded successfully.")
print("P1 target shape:", df_p1_split.shape)

print("\nColumns:")
print(df_p1_split.columns.tolist())

print("\nFirst 10 row_order values:")
print(df_p1_split["row_order"].head(10).tolist())

print("\nLast 10 row_order values:")
print(df_p1_split["row_order"].tail(10).tolist())

print("\nAgent class distribution:")
print(df_p1_split["agent"].value_counts(dropna=False))

P1 target data loaded successfully.
P1 target shape: (2743853, 3)

Columns:
['row_order', 'split', 'agent']

First 10 row_order values:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Last 10 row_order values:
[2743843, 2743844, 2743845, 2743846, 2743847, 2743848, 2743849, 2743850, 2743851, 2743852]

Agent class distribution:
agent
OpenAI_Codex    2069595
Copilot          349694
Cursor           212544
Google_Jules      50490
Devin             43298
Claude_Code       18232
Name: count, dtype: int64


In [4]:
# Separate target variable into train and test sets
# The data is already ordered by row_order.

y_train = df_p1_split.loc[
    df_p1_split["split"] == "train", "agent"
].reset_index(drop=True)

y_test = df_p1_split.loc[
    df_p1_split["split"] == "test", "agent"
].reset_index(drop=True)

print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

print("\nTraining class distribution:")
print(y_train.value_counts())

print("\nTesting class distribution:")
print(y_test.value_counts())

y_train shape: (2195082,)
y_test shape: (548771,)

Training class distribution:
agent
OpenAI_Codex    1655676
Copilot          279755
Cursor           170035
Google_Jules      40392
Devin             34638
Claude_Code       14586
Name: count, dtype: int64

Testing class distribution:
agent
OpenAI_Codex    413919
Copilot          69939
Cursor           42509
Google_Jules     10098
Devin             8660
Claude_Code       3646
Name: count, dtype: int64


In [5]:
# Validate P1 feature and target alignment

print("===== P1 DATA VALIDATION =====")

print("X_train rows:", X_train.shape[0])
print("y_train rows:", len(y_train))
print("X_test rows :", X_test.shape[0])
print("y_test rows :", len(y_test))

print("\nFeature count:", X_train.shape[1])
print("Number of classes:", y_train.nunique())

print("\nMissing values in y_train:", y_train.isna().sum())
print("Missing values in y_test :", y_test.isna().sum())

print("\nAlignment check:")
print("Train:", X_train.shape[0] == len(y_train))
print("Test :", X_test.shape[0] == len(y_test))

print("\nAgent classes:")
print(sorted(y_train.unique()))

===== P1 DATA VALIDATION =====
X_train rows: 2195082
y_train rows: 2195082
X_test rows : 548771
y_test rows : 548771

Feature count: 5330
Number of classes: 6

Missing values in y_train: 0
Missing values in y_test : 0

Alignment check:
Train: True
Test : True

Agent classes:
['Claude_Code', 'Copilot', 'Cursor', 'Devin', 'Google_Jules', 'OpenAI_Codex']


In [6]:
# Import classification algorithms

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

print("All classification algorithms imported successfully.")

All classification algorithms imported successfully.


In [8]:
# Create stratified sample for initial model comparison
# Full dataset is large, so models are compared on a representative sample.

from sklearn.model_selection import train_test_split

SAMPLE_TRAIN_SIZE = 100_000
SAMPLE_TEST_SIZE = 25_000

X_train_sample, _, y_train_sample, _ = train_test_split(
    X_train,
    y_train,
    train_size=SAMPLE_TRAIN_SIZE,
    stratify=y_train,
    random_state=42
)

X_test_sample, _, y_test_sample, _ = train_test_split(
    X_test,
    y_test,
    train_size=SAMPLE_TEST_SIZE,
    stratify=y_test,
    random_state=42
)

print("Sample created successfully.")
print("X_train_sample:", X_train_sample.shape)
print("y_train_sample:", y_train_sample.shape)
print("X_test_sample :", X_test_sample.shape)
print("y_test_sample :", y_test_sample.shape)

Sample created successfully.
X_train_sample: (100000, 5330)
y_train_sample: (100000,)
X_test_sample : (25000, 5330)
y_test_sample : (25000,)


In [9]:
# Define classification models for initial comparison

models = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        n_jobs=-1
    ),

    "KNN": KNeighborsClassifier(
        n_neighbors=5,
        n_jobs=-1
    ),

    "Naive Bayes": MultinomialNB(),

    "SVM": LinearSVC(
        class_weight="balanced",
        max_iter=5000
    ),

    "Decision Tree": DecisionTreeClassifier(
        class_weight="balanced",
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ),

    "XGBoost": XGBClassifier(
        n_estimators=100,
        max_depth=6,
        learning_rate=0.1,
        objective="multi:softmax",
        eval_metric="mlogloss",
        random_state=42,
        n_jobs=-1
    )
}

print("Models defined successfully:")
for name in models:
    print("-", name)

Models defined successfully:
- Logistic Regression
- KNN
- Naive Bayes
- SVM
- Decision Tree
- Random Forest
- XGBoost


---

## Logistic Regression

Logistic Regression is a linear classification algorithm used to predict the AI coding agent associated with a pull request. It provides a strong and interpretable baseline for multiclass classification.

In [11]:
# Train Logistic Regression on the model-study sample

lr_model = models["Logistic Regression"]

print("Training Logistic Regression...")

lr_model.fit(
    X_train_sample,
    y_train_sample
)

print("Logistic Regression training completed.")

lr_model

Training Logistic Regression...


c:\Users\srich\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:1457: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)


Logistic Regression training completed.


,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",'balanced'
,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"n_jobs n_jobs: int, default=NoneDoes not have any effect... deprecated:: 1.8 `n_jobs` is deprecated in version 1.8 and will be removed in 1.10.",-1
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None


In [12]:
# Logistic Regression Predictions

y_train_pred_lr = lr_model.predict(X_train_sample)
y_test_pred_lr = lr_model.predict(X_test_sample)

print("Train predictions shape:", y_train_pred_lr.shape)
print("Test predictions shape :", y_test_pred_lr.shape)

print("\nSample train predictions:")
print(y_train_pred_lr[:10])

print("\nSample test predictions:")
print(y_test_pred_lr[:10])

Train predictions shape: (100000,)
Test predictions shape : (25000,)

Sample train predictions:
['Copilot' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'Cursor'
 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'Copilot' 'OpenAI_Codex']

Sample test predictions:
['OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex'
 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex'
 'OpenAI_Codex' 'OpenAI_Codex']


In [14]:
# Logistic Regression Evaluation

lr_train_f1 = f1_score(
    y_train_sample,
    y_train_pred_lr,
    average="macro"
)

lr_test_f1 = f1_score(
    y_test_sample,
    y_test_pred_lr,
    average="macro"
)

lr_train_accuracy = accuracy_score(
    y_train_sample,
    y_train_pred_lr
)

lr_test_accuracy = accuracy_score(
    y_test_sample,
    y_test_pred_lr
)

print("Logistic Regression Evaluation")
print("--------------------------------")
print(f"Train F1 Score: {lr_train_f1}")
print(f"Test F1 Score: {lr_test_f1}")
print(f"Train Accuracy: {lr_train_accuracy}")
print(f"Test Accuracy: {lr_test_accuracy}")

Logistic Regression Evaluation
--------------------------------
Train F1 Score: 0.981876647315107
Test F1 Score: 0.9703938838354126
Train Accuracy: 0.99411
Test Accuracy: 0.99128


---

## K-Nearest Neighbors (KNN)

K-Nearest Neighbors classifies a pull request based on the classes of its nearest observations in the feature space. It is included to compare a distance-based approach with the other classification models.

In [15]:
# Train KNN

knn_model = models["KNN"]

print("Training KNN...")

knn_model.fit(
    X_train_sample,
    y_train_sample
)

print("KNN training completed.")

knn_model

Training KNN...
KNN training completed.


,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.Doesn't affect :meth:`fit` method.",-1
,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",5
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance<https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
Name,Type,Value
"classes_ classes_: array of shape (n_classes,)Class labels known to the classifier","ndarray[object](6,)","['Claude_Code','Copilot','Cursor','Devin','Google_Jules','OpenAI_Codex']"
"effective_metric_ effective_metric_: str or callbleThe distance metric used. It will be same as the `metric` parameteror a synonym of it, e.g. 'euclidean' if the `metric` parameter set to'minkowski' and `p` parameter set to 2.",str,'eu...an'


In [16]:
# KNN Predictions

y_train_pred_knn = knn_model.predict(X_train_sample)
y_test_pred_knn = knn_model.predict(X_test_sample)

print("Train predictions shape:", y_train_pred_knn.shape)
print("Test predictions shape :", y_test_pred_knn.shape)

print("\nSample train predictions:")
print(y_train_pred_knn[:10])

print("\nSample test predictions:")
print(y_test_pred_knn[:10])

Train predictions shape: (100000,)
Test predictions shape : (25000,)

Sample train predictions:
['Copilot' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'Cursor'
 'OpenAI_Codex' 'OpenAI_Codex' 'Cursor' 'Copilot' 'OpenAI_Codex']

Sample test predictions:
['OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex'
 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex'
 'OpenAI_Codex' 'OpenAI_Codex']


In [17]:
# KNN Evaluation

from sklearn.metrics import f1_score, accuracy_score

train_f1_knn = f1_score(
    y_train_sample,
    y_train_pred_knn,
    average="macro"
)

test_f1_knn = f1_score(
    y_test_sample,
    y_test_pred_knn,
    average="macro"
)

train_accuracy_knn = accuracy_score(
    y_train_sample,
    y_train_pred_knn
)

test_accuracy_knn = accuracy_score(
    y_test_sample,
    y_test_pred_knn
)

print("KNN Evaluation")
print("--------------")
print(f"Train F1 Score: {train_f1_knn}")
print(f"Test F1 Score: {test_f1_knn}")
print(f"Train Accuracy: {train_accuracy_knn}")
print(f"Test Accuracy: {test_accuracy_knn}")

KNN Evaluation
--------------
Train F1 Score: 0.814212095091687
Test F1 Score: 0.7400996217033974
Train Accuracy: 0.9555
Test Accuracy: 0.93292


---

## Naive Bayes

Naive Bayes is a probabilistic classification algorithm that is well suited to text-based features such as TF-IDF. It is used to evaluate how effectively textual information can identify the AI coding agent.

In [18]:
# Train Naive Bayes

nb_model = models["Naive Bayes"]

# Use only non-negative features for MultinomialNB
X_train_nb = X_train_sample[:, :5319]
X_test_nb = X_test_sample[:, :5319]

print("Training Naive Bayes...")

nb_model.fit(
    X_train_nb,
    y_train_sample
)

print("Naive Bayes training completed.")

nb_model

Training Naive Bayes...
Naive Bayes training completed.


,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)Number of samples encountered for each class during fitting. Thisvalue is weighted by the sample weight when provided.","ndarray[float64](6,)","[ 664.,12745., 7746., 1578., 1840.,75427.]"
"class_log_prior_ class_log_prior_: ndarray of shape (n_classes,)Smoothed empirical log probability for each class.","ndarray[float64](6,)","[-5.01,-2.06,-2.56,-4.15,-4. ,-0.28]"
"classes_ classes_: ndarray of shape (n_classes,)Class labels known to the classifier","ndarray[<U12](6,)","['Claude_Code','Copilot','Cursor','Devin','Google_Jules','OpenAI_Codex']"
"feature_count_ feature_count_: ndarray of shape (n_classes, n_features)Number of samples encountered for each (class, feature)during fitting. This value is weighted by the sample weight whenprovided.","ndarray[float64](6, 5319)","[[ 1.65, 0.5 , 0.9 ,..., 640. , 23. , 1. ], [ 23.47, 17.63, 14.36,...,11541. , 1173. , 31. ], [ 2.96, 2.02, 1.92,..., 7219. , 507. , 20. ], [ 0.95, 0.45, 4.21,..., 1365. , 213. , 0. ], [ 1.64, 0.52, 2.75,..., 1675. , 165. , 0. ], [ 34.38, 11.24, 21.14,...,70948. , 4214. , 265. ]]"
"feature_log_prob_ feature_log_prob_: ndarray of shape (n_classes, n_features)Empirical log probability of featuresgiven a class, ``P(x_i|y)``.","ndarray[float64](6, 5319)","[[ -8.52, -9.09, -8.85,..., -3.03, -6.32, -8.8 ], [ -8.95, -9.22, -9.41,..., -2.79, -5.08, -8.68], [ -9.9 ,-10.17,-10.21,..., -2.39, -5.05, -8.23], [ -9.39, -9.68, -8.4 ,..., -2.83, -4.69,-10.05], [ -9.04, -9.6 , -8.69,..., -2.59, -4.9 ,-10.01], [ -9.84,-10.9 ,-10.31,..., -2.24, -5.06, -7.82]]"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,5319


In [19]:
# Naive Bayes Predictions

y_train_pred_nb = nb_model.predict(X_train_nb)
y_test_pred_nb = nb_model.predict(X_test_nb)

print("Train predictions shape:", y_train_pred_nb.shape)
print("Test predictions shape :", y_test_pred_nb.shape)

print("\nSample train predictions:")
print(y_train_pred_nb[:10])

print("\nSample test predictions:")
print(y_test_pred_nb[:10])

Train predictions shape: (100000,)
Test predictions shape : (25000,)

Sample train predictions:
['Copilot' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'Cursor'
 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'Copilot' 'OpenAI_Codex']

Sample test predictions:
['OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex'
 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex'
 'OpenAI_Codex' 'OpenAI_Codex']


In [21]:
# Naive Bayes Evaluation

from sklearn.metrics import f1_score, accuracy_score

train_f1_nb = f1_score(
    y_train_sample,
    y_train_pred_nb,
    average="macro"
)

test_f1_nb = f1_score(
    y_test_sample,
    y_test_pred_nb,
    average="macro"
)

train_accuracy_nb = accuracy_score(
    y_train_sample,
    y_train_pred_nb
)

test_accuracy_nb = accuracy_score(
    y_test_sample,
    y_test_pred_nb
)

print("Naive Bayes Evaluation")
print("----------------------")
print(f"Train F1 Score: {train_f1_nb}")
print(f"Test F1 Score: {test_f1_nb}")
print(f"Train Accuracy: {train_accuracy_nb}")
print(f"Test Accuracy: {test_accuracy_nb}")

Naive Bayes Evaluation
----------------------
Train F1 Score: 0.9010316800738339
Test F1 Score: 0.8694193495329561
Train Accuracy: 0.97904
Test Accuracy: 0.97464


---

## Support Vector Machine (SVM)

Support Vector Machine is a classification algorithm that finds decision boundaries between classes. Linear SVM is used because the feature space contains high-dimensional TF-IDF and encoded features.

In [22]:
# Train SVM

svm_model = models["SVM"]

print("Training SVM...")

svm_model.fit(
    X_train_sample,
    y_train_sample
)

print("SVM training completed.")

svm_model

Training SVM...
SVM training completed.


,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to ``class_weight[i]*C`` forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",'balanced'
,"max_iter max_iter: int, default=1000The maximum number of iterations to be run.",5000
,"penalty penalty: {'l1', 'l2'}, default='l2'Specifies the norm used in the penalization. The 'l2'penalty is the standard used in SVC. The 'l1' leads to ``coef_``vectors that are sparse.",'l2'
,"loss loss: {'hinge', 'squared_hinge'}, default='squared_hinge'Specifies the loss function. 'hinge' is the standard SVM loss(used e.g. by the SVC class) while 'squared_hinge' is thesquare of the hinge loss. The combination of ``penalty='l1'``and ``loss='hinge'`` is not supported.",'squared_hinge'
,"dual dual: ""auto"" or bool, default=""auto""Select the algorithm to either solve the dual or primaloptimization problem. Prefer dual=False when n_samples > n_features.`dual=""auto""` will choose the value of the parameter automatically,based on the values of `n_samples`, `n_features`, `loss`, `multi_class`and `penalty`. If `n_samples` < `n_features` and optimizer supportschosen `loss`, `multi_class` and `penalty`, then dual will be set to True,otherwise it will be set to False... versionchanged:: 1.3 The `""auto""` option is added in version 1.3 and will be the default in version 1.5.",'auto'
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive.For an intuitive visualization of the effects of scalingthe regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"multi_class multi_class: {'ovr', 'crammer_singer'}, default='ovr'Determines the multi-class strategy if `y` contains more thantwo classes.``""ovr""`` trains n_classes one-vs-rest classifiers, while``""crammer_singer""`` optimizes a joint objective over all classes.While `crammer_singer` is interesting from a theoretical perspectiveas it is consistent, it is seldom used in practice as it rarely leadsto better accuracy and is more expensive to compute.If ``""crammer_singer""`` is chosen, the options loss, penalty and dualwill be ignored.",'ovr'
,"fit_intercept fit_intercept: bool, default=TrueWhether or not to fit an intercept. If set to True, the feature vectoris extended to include an intercept term: `[x_1, ..., x_n, 1]`, where1 corresponds to the intercept. If set to False, no intercept will beused in calculations (i.e. data is expected to be already centered).",True
,"intercept_scaling intercept_scaling: float, default=1.0When `fit_intercept` is True, the instance vector x becomes ``[x_1,..., x_n, intercept_scaling]``, i.e. a ""synthetic"" feature with aconstant value equal to `intercept_scaling` is appended to the instancevector. The intercept becomes intercept_scaling * synthetic featureweight. Note that liblinear internally penalizes the intercept,treating it like any other term in the feature vector. To reduce theimpact of the regularization on the intercept, the `intercept_scaling`parameter can be set to a value greater than 1; the higher the value of`intercept_scaling`, the lower the impact of regularization on it.Then, the weights become `[w_x_1, ..., w_x_n,w_intercept*intercept_scaling]`, where `w_x_1, ..., w_x_n` representthe feature weights and the intercept weight is scaled by`intercept_scaling`. This scaling allows the intercept term to have adifferent regularization behavior compared to the other features.",1
,"verbose verbose: int, default=0Enable verbose output. Note that this setting takes advantage of aper-process runtime setting in liblinear that, if enabled, may not workproperly in a multithreaded context.",0


In [23]:
# SVM Predictions

y_train_pred_svm = svm_model.predict(X_train_sample)
y_test_pred_svm = svm_model.predict(X_test_sample)

print("Train predictions shape:", y_train_pred_svm.shape)
print("Test predictions shape :", y_test_pred_svm.shape)

print("\nSample train predictions:")
print(y_train_pred_svm[:10])

print("\nSample test predictions:")
print(y_test_pred_svm[:10])

Train predictions shape: (100000,)
Test predictions shape : (25000,)

Sample train predictions:
['Copilot' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'Cursor'
 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'Copilot' 'OpenAI_Codex']

Sample test predictions:
['OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex'
 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex'
 'OpenAI_Codex' 'OpenAI_Codex']


In [24]:
# SVM Evaluation

from sklearn.metrics import f1_score, accuracy_score

train_f1_svm = f1_score(
    y_train_sample,
    y_train_pred_svm,
    average="macro"
)

test_f1_svm = f1_score(
    y_test_sample,
    y_test_pred_svm,
    average="macro"
)

train_accuracy_svm = accuracy_score(
    y_train_sample,
    y_train_pred_svm
)

test_accuracy_svm = accuracy_score(
    y_test_sample,
    y_test_pred_svm
)

print("SVM Evaluation")
print("--------------")
print(f"Train F1 Score: {train_f1_svm}")
print(f"Test F1 Score: {test_f1_svm}")
print(f"Train Accuracy: {train_accuracy_svm}")
print(f"Test Accuracy: {test_accuracy_svm}")

SVM Evaluation
--------------
Train F1 Score: 0.9973196355871213
Test F1 Score: 0.9777936487999934
Train Accuracy: 0.99892
Test Accuracy: 0.99284


---

## Decision Tree

Decision Tree is a tree-based classification algorithm that learns decision rules from the input features. It is included to evaluate a nonlinear and interpretable classification approach.

In [25]:
# Train Decision Tree

dt_model = models["Decision Tree"]

print("Training Decision Tree...")

dt_model.fit(
    X_train_sample,
    y_train_sample
)

print("Decision Tree training completed.")

dt_model

Training Decision Tree...
Decision Tree training completed.


,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary <random_state>` for details.",42
,"class_weight class_weight: dict, list of dict or ""balanced"", default=NoneWeights associated with classes in the form ``{class_label: weight}``.If None, all classes are supposed to have weight one. Formulti-output problems, a list of dicts can be provided in the sameorder as the columns of y.Note that for multioutput (including multilabel) weights should bedefined for each class of every column in its own dict. For example,for four-class multilabel classification weights should be[{0: 1, 1: 1}, {0: 1, 1: 5}, {0: 1, 1: 1}, {0: 1, 1: 1}] instead of[{1:1}, {2:5}, {3:1}, {4:1}].The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``For multi-output, the weights of each column of y will be multiplied.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified.",'balanced'
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.",'gini'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are 

In [26]:
# Decision Tree Predictions

y_train_pred_dt = dt_model.predict(X_train_sample)
y_test_pred_dt = dt_model.predict(X_test_sample)

print("Train predictions shape:", y_train_pred_dt.shape)
print("Test predictions shape :", y_test_pred_dt.shape)

print("\nSample train predictions:")
print(y_train_pred_dt[:10])

print("\nSample test predictions:")
print(y_test_pred_dt[:10])

Train predictions shape: (100000,)
Test predictions shape : (25000,)

Sample train predictions:
['Copilot' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'Cursor'
 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'Copilot' 'OpenAI_Codex']

Sample test predictions:
['OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex'
 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex'
 'OpenAI_Codex' 'OpenAI_Codex']


In [27]:
# Decision Tree Evaluation

from sklearn.metrics import f1_score, accuracy_score

train_f1_dt = f1_score(
    y_train_sample,
    y_train_pred_dt,
    average="macro"
)

test_f1_dt = f1_score(
    y_test_sample,
    y_test_pred_dt,
    average="macro"
)

train_accuracy_dt = accuracy_score(
    y_train_sample,
    y_train_pred_dt
)

test_accuracy_dt = accuracy_score(
    y_test_sample,
    y_test_pred_dt
)

print("Decision Tree Evaluation")
print("------------------------")
print(f"Train F1 Score: {train_f1_dt}")
print(f"Test F1 Score: {test_f1_dt}")
print(f"Train Accuracy: {train_accuracy_dt}")
print(f"Test Accuracy: {test_accuracy_dt}")

Decision Tree Evaluation
------------------------
Train F1 Score: 1.0
Test F1 Score: 0.9793357469734435
Train Accuracy: 1.0
Test Accuracy: 0.99256


---

## Random Forest

Random Forest is an ensemble classification algorithm that combines multiple decision trees to improve predictive performance and reduce the limitations of a single decision tree.

In [28]:
# Train Random Forest

rf_model = models["Random Forest"]

print("Training Random Forest...")

rf_model.fit(
    X_train_sample,
    y_train_sample
)

print("Random Forest training completed.")

rf_model

Training Random Forest...
Random Forest training completed.


,"n_jobs n_jobs: int, default=NoneThe number of jobs to run in parallel. :meth:`fit`, :meth:`predict`,:meth:`decision_path` and :meth:`apply` are all parallelized over thetrees. ``None`` means 1 unless in a :obj:`joblib.parallel_backend`context. ``-1`` means using all processors. See :term:`Glossary<n_jobs>` for more details.",-1
,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"class_weight class_weight: {""balanced"", ""balanced_subsample""}, dict or list of dicts, default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one. Formulti-output problems, a list of dicts can be provided in the sameorder as the columns of y.Note that for multioutput (including multilabel) weights should bedefined for each class of every column in its own dict. For example,for four-class multilabel classification weights should be[{0: 1, 1: 1}, {0: 1, 1: 5}, {0: 1, 1: 1}, {0: 1, 1: 1}] instead of[{1:1}, {2:5}, {3:1}, {4:1}].The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``The ""balanced_subsample"" mode is the same as ""balanced"" except thatweights are computed based on the bootstrap sample for every treegrown.For multi-output, the weights of each column of y will be multiplied.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified.",'balanced'
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_fe

In [29]:
# Random Forest Predictions

y_train_pred_rf = rf_model.predict(X_train_sample)
y_test_pred_rf = rf_model.predict(X_test_sample)

print("Train predictions shape:", y_train_pred_rf.shape)
print("Test predictions shape :", y_test_pred_rf.shape)

print("\nSample train predictions:")
print(y_train_pred_rf[:10])

print("\nSample test predictions:")
print(y_test_pred_rf[:10])

Train predictions shape: (100000,)
Test predictions shape : (25000,)

Sample train predictions:
['Copilot' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'Cursor'
 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'Copilot' 'OpenAI_Codex']

Sample test predictions:
['OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex'
 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex'
 'OpenAI_Codex' 'OpenAI_Codex']


In [30]:
# Random Forest Evaluation

from sklearn.metrics import f1_score, accuracy_score

train_f1_rf = f1_score(
    y_train_sample,
    y_train_pred_rf,
    average="macro"
)

test_f1_rf = f1_score(
    y_test_sample,
    y_test_pred_rf,
    average="macro"
)

train_accuracy_rf = accuracy_score(
    y_train_sample,
    y_train_pred_rf
)

test_accuracy_rf = accuracy_score(
    y_test_sample,
    y_test_pred_rf
)

print("Random Forest Evaluation")
print("------------------------")
print(f"Train F1 Score: {train_f1_rf}")
print(f"Test F1 Score: {test_f1_rf}")
print(f"Train Accuracy: {train_accuracy_rf}")
print(f"Test Accuracy: {test_accuracy_rf}")

Random Forest Evaluation
------------------------
Train F1 Score: 0.9973238150984228
Test F1 Score: 0.9811993655839776
Train Accuracy: 0.99788
Test Accuracy: 0.99232


---

## XGBoost

XGBoost is a gradient-boosting algorithm that builds an ensemble of sequential decision trees. It is evaluated as a powerful nonlinear model for identifying the AI coding agent from pull request features.

In [ ]:
# XGBoost requires class labels to be represented as numeric
# values, so the agent labels are encoded before training.
# Train XGBoost

from sklearn.preprocessing import LabelEncoder

xgb_model = models["XGBoost"]

# Encode agent labels for XGBoost
label_encoder_xgb = LabelEncoder()

y_train_xgb = label_encoder_xgb.fit_transform(y_train_sample)

print("Training XGBoost...")

xgb_model.fit(
    X_train_sample,
    y_train_xgb
)

print("XGBoost training completed.")

xgb_model

Training XGBoost...
XGBoost training completed.


,"objective objective: str | xgboost.objective.Objective | xgboost.sklearn._SklObjWProto | typing.Callable[[typing.Any, typing.Any], typing.Tuple[numpy.ndarray, numpy.ndarray]] | NoneSpecify the learning task and the corresponding learning objective or a customobjective to be used.For custom objective, see :doc:`/tutorials/custom_metric_obj` and:ref:`custom-obj-metric` for more information, along with the end note forfunction signatures.",'multi:softmax'
,"base_score base_score: float | typing.List[float] | NoneThe initial prediction score of all instances, global bias.",None
,booster,None
,"callbacks callbacks: typing.List[xgboost.callback.TrainingCallback] | NoneList of callback functions that are applied at end of each iteration.It is possible to use predefined callbacks by using:ref:`Callback API <callback_api>`... note:: States in callback are not preserved during training, which means callback objects can not be reused for multiple training sessions without reinitialization or deepcopy... code-block:: python for params in parameters_grid: # be sure to (re)initialize the callbacks before each run callbacks = [xgb.callback.LearningRateScheduler(custom_rates)] reg = xgboost.XGBRegressor(**params, callbacks=callbacks) reg.fit(X, y)",None
,colsample_bylevel colsample_bylevel: float | NoneSubsample ratio of columns for each level.,None
,colsample_bynode colsample_bynode: float | NoneSubsample ratio of columns for each split.,None
,colsample_bytree colsample_bytree: float | NoneSubsample ratio of columns when constructing each tree.,None
,"device device: str | None.. versionadded:: 2.0.0Device ordinal, available options are `cpu`, `cuda`, and `gpu`.",None
,"early_stopping_rounds early_stopping_rounds: int | None.. versionadded:: 1.6.0- Activates early stopping. Validation metric needs to improve at least once in every **early_stopping_rounds** round(s) to continue training. Requires at least one item in **eval_set** in :py:meth:`fit`.- If early stopping occurs, the model will have two additional attributes: :py:attr:`best_score` and :py:attr:`best_iteration`. These are used by the :py:meth:`predict` and :py:meth:`apply` methods to determine the optimal number of trees during inference. If users want to access the full model (including trees built after early stopping), they can specify the `iteration_range` in these inference methods. In addition, other utilities like model plotting can also use the entire model.- If you prefer to discard the trees after `best_iteration`, consider using the callback function :py:class:`xgboost.callback.EarlyStopping`.- If there's more than one item in **eval_set**, the last entry will be used for early stopping. If there's more than one metric in **eval_metric**, the last metric will be used for early stopping.",None
,enable_categorical enable_categorical: boolSee the same parameter of :py:class:`DMatrix` for details.,True
,"eval_metric eval_metric: str | typing.List[str | typing.Callable] | typing.Callable | None.. versionadded:: 1.6.0Metric used for monitoring the training result and early stopping. It can be astring or list of strings as names of predefined metric in XGBoost (See:doc:`/parameter`), one of the metrics in :py:mod:`sklearn.metrics`, or anyother user defined metric that looks like `sklearn.metrics`.If custom objective is also provided, then custom metric should implement thecorresponding reverse link function.Unlike the `scoring` parameter commonly used in scikit-learn, when a callableobject is provided, it's assumed to be a cost function and by default XGBoostwill minimize the result during early stopping.For advanced usage on Early stopping like directly choosing to maximize insteadof minimize, see :py:obj:`xgboost.callback.EarlyStopping`.See :doc:`/tutorials/custom_metric_obj` and :ref:`custom-obj-metric` for moreinformation... code-block:: python from sklearn.datasets import load_diabetes from sklearn.metrics import mean_absolute_error X, y = load_diabetes(return_X_y=True) r

In [32]:
# XGBOOST — PREDICTIONS
# XGBoost returns numeric class labels. They are decoded back
# to the original agent names for evaluation.

y_train_pred_xgb_encoded = xgb_model.predict(
    X_train_sample
)

y_test_pred_xgb_encoded = xgb_model.predict(
    X_test_sample
)

y_train_pred_xgb = label_encoder_xgb.inverse_transform(
    y_train_pred_xgb_encoded.astype(int)
)

y_test_pred_xgb = label_encoder_xgb.inverse_transform(
    y_test_pred_xgb_encoded.astype(int)
)

print("Train predictions shape:", y_train_pred_xgb.shape)
print("Test predictions shape :", y_test_pred_xgb.shape)

print("\nSample train predictions:")
print(y_train_pred_xgb[:10])

print("\nSample test predictions:")
print(y_test_pred_xgb[:10])

Train predictions shape: (100000,)
Test predictions shape : (25000,)

Sample train predictions:
['Copilot' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'Cursor'
 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'Copilot' 'OpenAI_Codex']

Sample test predictions:
['OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex'
 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex' 'OpenAI_Codex'
 'OpenAI_Codex' 'OpenAI_Codex']


In [33]:
# XGBOOST — EVALUATION
# Macro F1 is used because the agent classes are imbalanced.

from sklearn.metrics import f1_score, accuracy_score

train_f1_xgb = f1_score(
    y_train_sample,
    y_train_pred_xgb,
    average="macro"
)

test_f1_xgb = f1_score(
    y_test_sample,
    y_test_pred_xgb,
    average="macro"
)

train_accuracy_xgb = accuracy_score(
    y_train_sample,
    y_train_pred_xgb
)

test_accuracy_xgb = accuracy_score(
    y_test_sample,
    y_test_pred_xgb
)

print("XGBoost Evaluation")
print("------------------")
print(f"Train F1 Score: {train_f1_xgb}")
print(f"Test F1 Score: {test_f1_xgb}")
print(f"Train Accuracy: {train_accuracy_xgb}")
print(f"Test Accuracy: {test_accuracy_xgb}")

XGBoost Evaluation
------------------
Train F1 Score: 0.9988492842925569
Test F1 Score: 0.9914525668172608
Train Accuracy: 0.999
Test Accuracy: 0.99592


---

## Bias-Variance Trade-off

The difference between training and testing F1 scores is analyzed to determine whether each classification model is underfitting, overfitting, or providing a good fit.

In [34]:
# Bias-Variance Trade-off — Classification

def classify_fit(train_score, test_score):
    gap = train_score - test_score

    if gap <= 0.03:
        return "Goodfit"
    elif gap > 0.10:
        return "Overfit"
    else:
        return "Goodfit"


bias_variance_results = []

model_scores = {
    "LR": (lr_train_f1, lr_test_f1),
    "KNN": (train_f1_knn, test_f1_knn),
    "NB": (train_f1_nb, test_f1_nb),
    "SVM": (train_f1_svm, test_f1_svm),
    "DT": (train_f1_dt, test_f1_dt),
    "RF": (train_f1_rf, test_f1_rf),
    "XGB": (train_f1_xgb, test_f1_xgb)
}

for model_name, (train_score, test_score) in model_scores.items():

    fit = classify_fit(train_score, test_score)

    bias_variance_results.append({
        "Models": model_name,
        "TrainScore (F1)": train_score,
        "TestScore (F1)": test_score,
        "Bias-Variance (Fit)": fit
    })

bias_variance_df = pd.DataFrame(bias_variance_results)

print("===== BIAS-VARIANCE TRADE-OFF =====")

display(bias_variance_df)

===== BIAS-VARIANCE TRADE-OFF =====


,Models,TrainScore (F1),TestScore (F1),Bias-Variance (Fit)
0,LR,0.981877,0.970394,Goodfit
1,KNN,0.814212,0.740100,Goodfit
2,NB,0.901032,0.869419,Goodfit
3,SVM,0.997320,0.977794,Goodfit
4,DT,1.000000,0.979336,Goodfit
5,RF,0.997324,0.981199,Goodfit
6,XGB,0.998849,0.991453,Goodfit


---

## Cross-Validation

Cross-validation is performed to evaluate the generalization performance of the classification models across multiple validation folds. The mean F1 Score is used to compare the models and identify the most reliable model before hyperparameter tuning.

In [ ]:
# CROSS-VALIDATION

from sklearn.model_selection import cross_val_score

cv_results = {}

for name, model in models.items():

    print(f"Running Cross-Validation for {name}...")

    if name == "Naive Bayes":
        scores = cross_val_score(
            model,
            X_train_nb,
            y_train_sample,
            cv=5,
            scoring="f1_macro",
            n_jobs=-1
        )
    elif name == "XGBoost":
        y_train_cv = label_encoder_xgb.transform(y_train_sample)

        scores = cross_val_score(
            model,
            X_train_sample,
            y_train_cv,
            cv=5,
            scoring="f1_macro",
            n_jobs=-1
        )
    else:
        scores = cross_val_score(
            model,
            X_train_sample,
            y_train_sample,
            cv=5,
            scoring="f1_macro",
            n_jobs=-1
        )

    cv_results[name] = scores.mean()

    print(f"Mean CV F1 Score: {scores.mean():.6f}")
    print()

print("Cross-validation completed.")

Running Cross-Validation for Logistic Regression...
Mean CV F1 Score: 0.964169

Running Cross-Validation for KNN...
Mean CV F1 Score: 0.732469

Running Cross-Validation for Naive Bayes...
Mean CV F1 Score: 0.843176

Running Cross-Validation for SVM...
Mean CV F1 Score: 0.974992

Running Cross-Validation for Decision Tree...
Mean CV F1 Score: 0.975749

Running Cross-Validation for Random Forest...
Mean CV F1 Score: 0.984081

Running Cross-Validation for XGBoost...
Mean CV F1 Score: 0.991915

Cross-validation completed.


---

# Final Model Training

The selected XGBoost model is now trained on the complete training dataset to make use of all available training samples.

- The complete training feature matrix contains 2,195,082 observations.
- The model configuration selected during the model study is retained.
- The complete test dataset will be used for final performance evaluation.
- This step produces the final classification model for deployment and real-time prediction.

In [39]:
# FINAL XGBOOST — TARGET ENCODING

label_encoder_final = LabelEncoder()

y_train_final = label_encoder_final.fit_transform(y_train)
y_test_final = label_encoder_final.transform(y_test)

print("Target encoding completed.")
print("Number of classes:", len(label_encoder_final.classes_))
print("Classes:", label_encoder_final.classes_)

Target encoding completed.
Number of classes: 6
Classes: ['Claude_Code' 'Copilot' 'Cursor' 'Devin' 'Google_Jules' 'OpenAI_Codex']


In [40]:
# FINAL XGBOOST — MODEL SETUP

xgb_final = XGBClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    objective="multi:softmax",
    eval_metric="mlogloss",
    random_state=42,
    n_jobs=-1
)

print("Final XGBoost model created.")

Final XGBoost model created.


In [41]:
# Final XGBoost Training

print("Training XGBoost on the complete training dataset...")

xgb_final.fit(
    X_train,
    y_train_final
)

print("Final XGBoost training completed.")

Training XGBoost on the complete training dataset...
Final XGBoost training completed.


In [42]:
# Final XGBoost Predictions

y_train_pred_final = xgb_final.predict(X_train)
y_test_pred_final = xgb_final.predict(X_test)

y_train_pred_final = label_encoder_final.inverse_transform(
    y_train_pred_final.astype(int)
)

y_test_pred_final = label_encoder_final.inverse_transform(
    y_test_pred_final.astype(int)
)

print("Final predictions completed.")

Final predictions completed.


In [43]:
# Final XGBoost Evaluation

from sklearn.metrics import f1_score, accuracy_score

final_train_f1 = f1_score(
    y_train,
    y_train_pred_final,
    average="macro"
)

final_test_f1 = f1_score(
    y_test,
    y_test_pred_final,
    average="macro"
)

final_train_accuracy = accuracy_score(
    y_train,
    y_train_pred_final
)

final_test_accuracy = accuracy_score(
    y_test,
    y_test_pred_final
)

print("Final XGBoost Performance")
print("-------------------------")
print(f"Train F1 Score: {final_train_f1:.6f}")
print(f"Test F1 Score: {final_test_f1:.6f}")
print(f"Train Accuracy: {final_train_accuracy:.6f}")
print(f"Test Accuracy: {final_test_accuracy:.6f}")

Final XGBoost Performance
-------------------------
Train F1 Score: 0.996262
Test F1 Score: 0.994276
Train Accuracy: 0.997977
Test Accuracy: 0.997555


---

# Hyperparameter Tuning

Hyperparameter tuning is performed only if required to further improve model performance.

- The evaluated classification models are already showing strong performance on the test data.
- Cross-validation results are also consistent with the test performance, indicating good model generalization.
- XGBoost achieved the best overall performance among the evaluated models.
- Therefore, further hyperparameter tuning is not required, and the existing XGBoost configuration will be used for final training on the complete dataset.

---

## Final Model Comparison

The classification models are compared using Training F1 Score, Test F1 Score, Bias-Variance Fit, and Cross-Validation Score. These results are used to identify the best-performing model for the final classification task.

In [44]:
# Final Classification Model Comparison

classification_results = pd.DataFrame({
    "Models": ["LR", "KNN", "NB", "SVM", "DT", "RF", "XGB"],
    "TrainScore (F1)": [
        lr_train_f1,
        train_f1_knn,
        train_f1_nb,
        train_f1_svm,
        train_f1_dt,
        train_f1_rf,
        final_train_f1
    ],
    "TestScore (F1)": [
        lr_test_f1,
        test_f1_knn,
        test_f1_nb,
        test_f1_svm,
        test_f1_dt,
        test_f1_rf,
        final_test_f1
    ],
    "Bias-Variance (Fit)": [
        "Goodfit",
        "Goodfit",
        "Goodfit",
        "Goodfit",
        "Goodfit",
        "Goodfit",
        "Goodfit"
    ],
    "CrossValidation (TestScore)": [
        cv_results["Logistic Regression"],
        cv_results["KNN"],
        cv_results["Naive Bayes"],
        cv_results["SVM"],
        cv_results["Decision Tree"],
        cv_results["Random Forest"],
        cv_results["XGBoost"]
    ]
})

display(classification_results)

,Models,TrainScore (F1),TestScore (F1),Bias-Variance (Fit),CrossValidation (TestScore)
0,LR,0.981877,0.970394,Goodfit,0.964169
1,KNN,0.814212,0.740100,Goodfit,0.732469
2,NB,0.901032,0.869419,Goodfit,0.843176
3,SVM,0.997320,0.977794,Goodfit,0.974992
4,DT,1.000000,0.979336,Goodfit,0.975749
5,RF,0.997324,0.981199,Goodfit,0.984081
6,XGB,0.996262,0.994276,Goodfit,0.991915


## Final Model Selection

Based on the model comparison and cross-validation results, XGBoost is selected as the final classification model.

- XGBoost achieved the highest Test F1 Score of 0.994276.
- It achieved a Cross-Validation F1 Score of 0.991915, showing consistent performance.
- The small difference between training and testing performance indicates good generalization.
- The final XGBoost model is therefore selected for saving and real-time prediction.

---

# Saving Model & Real-Time Prediction

The trained, evaluated, and selected XGBoost model is saved for future use. The saved model can be loaded later and used to make predictions on unseen data using the same preprocessing and label encoding used during model training.

In [ ]:
# Save Final XGBoost Model

import joblib

joblib.dump(
    xgb_final,
    "../models/xgb_final.pkl"
)

print("Final XGBoost model saved successfully.")

Final XGBoost model saved successfully.


In [47]:
# Save Final Label Encoder

import joblib

joblib.dump(
    label_encoder_final,
    "../models/label_encoder_final.pkl"
)

print("Final label encoder saved successfully.")

Final label encoder saved successfully.


---

## Real-Time Prediction

The saved XGBoost model is loaded and used to predict the AI coding agent for unseen data. The same feature engineering and preprocessing steps used during training are applied to the new input before generating the prediction.

In [48]:
# Load Saved XGBoost Model

import joblib

loaded_xgb_model = joblib.load(
    "../models/xgb_final.pkl"
)

print("Saved XGBoost model loaded successfully.")

Saved XGBoost model loaded successfully.


In [49]:
# Load Saved Label Encoder

loaded_label_encoder = joblib.load(
    "../models/label_encoder_final.pkl"
)

print("Saved label encoder loaded successfully.")
print("Classes:", loaded_label_encoder.classes_)

Saved label encoder loaded successfully.
Classes: ['Claude_Code' 'Copilot' 'Cursor' 'Devin' 'Google_Jules' 'OpenAI_Codex']


In [50]:
# Prepare Unseen Data for Prediction

new_pr = pd.DataFrame([{
    "title": "Fix authentication issue in API",
    "body": "Updated the authentication logic and added tests for the API.",
    "language": "Python",
    "forks": 25,
    "stars": 120,
    "is_forked": False,
    "followers": 150,
    "following": 80,
    "user_account_age_days": 900,
    "title_length": 31,
    "body_length": 66,
    "created_year": 2026,
    "created_month": 9,
    "created_dayofweek": 5,
    "created_hour": 10
}])

print("Unseen input created.")
display(new_pr)

Unseen input created.


,title,body,language,forks,stars,is_forked,followers,following,user_account_age_days,title_length,body_length,created_year,created_month,created_dayofweek,created_hour
0,Fix authentication issue in API,Updated the authentication logic and added tes...,Python,25,120,False,150,80,900,31,66,2026,9,5,10


In [53]:
# Load P1 Preprocessing Artifacts

p1_title_vectorizer = joblib.load(
    "../models/p1_title_vectorizer.pkl"
)

p1_body_vectorizer = joblib.load(
    "../models/p1_body_vectorizer.pkl"
)

p1_encoder = joblib.load(
    "../models/p1_encoder.pkl"
)

p1_imputer = joblib.load(
    "../models/p1_imputer.pkl"
)

p1_scaler = joblib.load(
    "../models/p1_scaler.pkl"
)

print("P1 preprocessing artifacts loaded successfully.")

P1 preprocessing artifacts loaded successfully.


In [54]:
# Prepare Unseen Input Features

title_text = new_pr["title"].fillna("")
body_text = new_pr["body"].fillna("")

categorical_features = new_pr[
    ["language", "is_forked"]
]

numerical_features = new_pr[
    [
        "forks",
        "stars",
        "followers",
        "following",
        "user_account_age_days",
        "title_length",
        "body_length",
        "created_year",
        "created_month",
        "created_dayofweek",
        "created_hour"
    ]
]

print("Unseen input features prepared.")

Unseen input features prepared.


In [55]:
# Transform Unseen Title

new_title_tfidf = p1_title_vectorizer.transform(title_text)

print("Title transformation completed.")
print("Title TF-IDF shape:", new_title_tfidf.shape)

Title transformation completed.
Title TF-IDF shape: (1, 2000)


In [56]:
# Transform Unseen Body

new_body_tfidf = p1_body_vectorizer.transform(body_text)

print("Body transformation completed.")
print("Body TF-IDF shape:", new_body_tfidf.shape)

Body transformation completed.
Body TF-IDF shape: (1, 3000)


In [59]:
# Prepare Categorical Features for Encoding

categorical_features = new_pr[
    ["language", "is_forked"]
].copy()

categorical_features["is_forked"] = categorical_features["is_forked"].map({
    False: "0.0",
    True: "1.0"
})

print("Categorical input adjusted to training format.")
display(categorical_features)

Categorical input adjusted to training format.


,language,is_forked
0,Python,0.0


In [60]:
# Encode Unseen Categorical Features

new_encoded = p1_encoder.transform(categorical_features)

print("Categorical transformation completed.")
print("Encoded shape:", new_encoded.shape)

Categorical transformation completed.
Encoded shape: (1, 319)


In [61]:
# Prepare Unseen Numerical Features

new_numeric_imputed = p1_imputer.transform(numerical_features)

new_numeric_scaled = p1_scaler.transform(new_numeric_imputed)

print("Numerical transformation completed.")
print("Scaled shape:", new_numeric_scaled.shape)

Numerical transformation completed.
Scaled shape: (1, 11)


In [63]:
# Import Feature Stacking Function

from scipy.sparse import hstack

# Combine Unseen Features

new_pr_processed = hstack([
    new_encoded,
    new_numeric_scaled,
    new_title_tfidf,
    new_body_tfidf
]).tocsr().astype("float32")

print("Unseen features combined successfully.")
print("Processed shape:", new_pr_processed.shape)

Unseen features combined successfully.
Processed shape: (1, 5330)


In [64]:

# Generate Prediction for Unseen Data

prediction_encoded = loaded_xgb_model.predict(new_pr_processed)

prediction = loaded_label_encoder.inverse_transform(
    prediction_encoded.astype(int)
)

print("Predicted AI Coding Agent:", prediction[0])

Predicted AI Coding Agent: OpenAI_Codex


In [65]:
# Display Real-Time Prediction Result

print("Real-Time Prediction")
print("--------------------")
print("PR Title:", new_pr["title"].iloc[0])
print("PR Language:", new_pr["language"].iloc[0])
print("Predicted AI Coding Agent:", prediction[0])

Real-Time Prediction
--------------------
PR Title: Fix authentication issue in API
PR Language: Python
Predicted AI Coding Agent: OpenAI_Codex


## Classification Conclusion

The classification models were evaluated using Test F1 Score, Accuracy, Bias-Variance Fit, and Cross-Validation.

- XGBoost was selected as the final classification model based on its highest overall performance.
- The final model achieved a Test F1 Score of 0.994276 and Test Accuracy of 0.997555 on the complete test dataset.
- The final XGBoost model was saved and successfully loaded for future predictions.
- Real-time prediction was successfully demonstrated on unseen data, where the model predicted OpenAI_Codex as the AI coding agent.

---